name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.9
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  intl: ^0.20.2
  google_fonts: ^6.2.1	
  google_sign_in: ^6.3.0
  fl_chart: ^0.66.0
  cached_network_image: ^3.4.1
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_filex: ^4.7.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/homeOffice.jpg
    - assets/fLogo.png
    - assets/fLogoBlanco.png
    - assets/fLogoVerde.png
    - assets/LogoCompleto.png
    - assets/google.png
    - assets/linkedin.png
    - assets/github.png
    - assets/apple.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
